// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbfntsemffbgjoeartoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZm50c2VtZmZiZ2pvZWFydG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjQ5NzksImV4cCI6MjA1NTk0MDk3OX0.CQ6OheNa6jrMuQPnlXPHTp-eExUB4GhnRVOGscZx3D4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});